### ISSUE TITLE
Not an issue, but wanted to thank for MD endgame keymap

### ISSUE THREAD

**Issue by hlmtre** [ash0x0/config#1]
Hopefully this isn't too creepy, but I've got a Massdrop CTRL as well and am getting into my first foray into writing a qmk firmware for it. I've shameless cribbed yours as my baseline to modify, and I wanted to thank you for the well organized code and examples of everything.

My email is listed on my profile if you'd like to write back via more traditional methods.

**Comment by ash0x0** [comment]
Thank you so much for taking the time to write this. Really glad someone is making use of the keymap. I'll probably be working on the ctrl for a long time so tons more stuff to come. Join QMK discord if you haven't, everyone who works on qmk is there and they're all extremely nice and helpful. Make sure to check [this](https://github.com/qmk/qmk_firmware/pull/6068) out and [this](https://github.com/qmk/qmk_firmware/pull/6568) for some goodies that haven't been merged in yet, the former one is the more useful one. Let me know if you ever have suggestions for endgame or other work on the ctrl here or on discord or in one of the keymap PRs. I'm working on a chibios port as well now to use qmk in full glory, hopefully it'll be done soon.
